#pragma kernel CSMain
RWTexture2D<float> Result : register(u0);
RWTexture2D<float4> NormalResult : register(u1);
StructuredBuffer<float4> Particles : register(t0);

int ParticleCount;
int2 TextureSize;
float2 RegionCenter;
float2 RegionSize;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)TextureSize.x || id.y >= (uint)TextureSize.y)
        return;

    float2 uv = float2(id.x, id.y) / float2(TextureSize);    // [0,1]
    float2 worldPos = RegionCenter + (uv - 0.5f) * RegionSize;

    float height = 0.0f;

    for (int i = 0; i < ParticleCount; i++)
    {
        float2 particleWorldPos = Particles[i].xy;  // 粒子坐标必须和 region 匹配
        float particleHeight = Particles[i].z;
        float radius = max(Particles[i].w, 1e-2f); // 防止为0

        float2 delta = worldPos - particleWorldPos;
        float dist = length(delta);
        if (dist < radius)
        {
            float t = saturate(dist / radius);
            float weight = cos(t * 3.1415926f) * 0.5f + 0.5f;
            height += particleHeight * weight;
        }
    }

    // 中心差分采样法
    float dx = RegionSize.x / TextureSize.x;
    float dy = RegionSize.y / TextureSize.y;

    float heightR = 0.0f;
    float2 worldPosR = worldPos + float2(dx, 0);
    for (int i = 0; i < ParticleCount; i++)
    {
        float2 particleWorldPos = Particles[i].xy;
        float particleHeight = Particles[i].z;
        float radius = Particles[i].w;
        float2 delta = worldPosR - particleWorldPos;
        float dist = length(delta);
        if (dist < radius)
        {
            float t = saturate(dist / radius);
            float weight = cos(t * 3.1415926f) * 0.5f + 0.5f;
            heightR += particleHeight * weight;
        }
    }
    float heightU = 0.0f;
    float2 worldPosU = worldPos + float2(0, dy);
    for (int i = 0; i < ParticleCount; i++)
    {
        float2 particleWorldPos = Particles[i].xy;
        float particleHeight = Particles[i].z;
        float radius = Particles[i].w;
        float2 delta = worldPosU - particleWorldPos;
        float dist = length(delta);
        if (dist < radius)
        {
            float t = saturate(dist / radius);
            float weight = cos(t * 3.1415926f) * 0.5f + 0.5f;
            heightU += particleHeight * weight;
        }
    }

    float3 dxVec = float3(dx, heightR - height, 0);
    float3 dzVec = float3(0, heightU - height, dy);
    float3 normal = normalize(cross(dzVec, dxVec));

    Result[id.xy] = height;
    NormalResult[id.xy] = float4(normal * 0.5 + 0.5, 1.0);
}
