// SeparableFilterCS.compute
#pragma kernel Horizontal
#pragma kernel Vertical

// 输入：原始“能量图”（脉冲/幅值都累在 .g）
// Horizontal 时：读原图 -> 写 X 向结果
// Vertical   时：读 X 向结果 -> 写最终高度
Texture2DArray<float>    InputArray;
RWTexture2DArray<float>  OutputArray;

int2   TexSize;           // (W,H)
int    Slice;             // 当前 slice
float2 RegionSize;        // (sx,sy) 世界尺寸
float  RadiusWorld;       // 扩散半径 世界单位

static const float PI = 3.14159265358979323846;

float texelWorldX() { return RegionSize.x / TexSize.x; }
float texelWorldY() { return RegionSize.y / TexSize.y; }

// ------------------------------
// Horizontal: 只沿 X 做 raised-cosine 偶对称扩散
// ------------------------------
[numthreads(8, 8, 1)]
void Horizontal(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= TexSize.x || id.y >= TexSize.y) return;

    const float texW = texelWorldX();
    const int   taps = int(RadiusWorld / texW);

    // 中心值（d=0 时权重=1）
    float h = InputArray[int3(id.xy, Slice)];
    if (h == 0) {
        return;
    }
    OutputArray[int3(id.xy, Slice)] += h;
    // 对称采样：左右各取 1..taps
    [loop]
    for (int off = 1; off <= taps; ++off)
    {
        float d = off * texW;
        float wc = 0.5 * (cos(PI * d / RadiusWorld) + 1.0);  // raised-cosine

        int2 pL = int2(max(id.x - off, 0), id.y);
        int2 pR = int2(min(id.x + off, TexSize.x - 1), id.y);


        OutputArray[int3(pL, Slice)] += h * wc;
        OutputArray[int3(pR, Slice)] += h * wc;
    }
    //OutputArray[int3(id.xy, Slice)] = float4(0, h, 0, 1);
}

// ------------------------------
// Vertical: 读取 X 结果，沿 Y 再做一次相同核 → 最终高度
// ------------------------------
[numthreads(8, 8, 1)]
void Vertical(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= TexSize.x || id.y >= TexSize.y) return;

    const float texH = texelWorldY();
    const int   taps = int(RadiusWorld / texH);

    // 中心值（d=0 时权重=1）
    float h = InputArray[int3(id.xy, Slice)];

    if (h == 0) {
        return;
    }
    OutputArray[int3(id.xy, Slice)] += h;
    [loop]
    for (int off = 1; off <= taps; ++off)
    {
        float d = off * texH;
        float wc = 0.5 * (cos(PI * d / RadiusWorld) + 1.0);

        int2 pB = int2(id.x, max(id.y - off, 0));
        int2 pT = int2(id.x, min(id.y + off, TexSize.y - 1));

        OutputArray[int3(pB, Slice)] += h * wc;
        OutputArray[int3(pT, Slice)] += h * wc;
    }
}
